export const monsterColumnDescriptor = [
  {
    field: 'name',
    headerName: 'Name',
    flex: 1,
    sortable: true,
    filterable: true,
  },
  {
    field: 'AC',
    flex: 1,
    sortable: true,
    filterable: true,
  },
  {
    field: 'HP',
    flex: 1,
    sortable: true,
    filterable: true,
  },
  {
    field: 'Speed',
    flex: 1,
    sortable: true,
    filterable: true,
  },
  {
    field: 'STR',
    flex: 0.25,
    sortable: true,
    filterable: true,
  },
  {
    field: 'DEX',
    flex: 0.25,
    sortable: true,
    filterable: true,
  },
  {
    field: 'CON',
    flex: 0.25,
    sortable: true,
    filterable: true,
  },
  {
    field: 'INT',
    flex: 0.25,
    sortable: true,
    filterable: true,
  },
  {
    field: 'WIS',
    flex: 0.25,
    sortable: true,
    filterable: true,
  },
  {
    field: 'CHA',
    flex: 0.25,
    sortable: true,
    filterable: true,
  },
  {
    field: 'Senses',
    flex: 1,
    sortable: true,
    filterable: true,
  },
  {
    field: 'Challenge',
    flex: 1,
    sortable: true,
    filterable: true,
  },
];
