services:

  postgres:
    image: postgres
    container_name: postgres
    restart: always
    shm_size: 128mb
    volumes:
      - type: tmpfs
        target: /dev/shm_size
        tmpfs:
          size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_USER: postgres # TODO: Remove hardcoding
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: dnd_assistant
    networks:
      - postgresnetwork

  adminer:
    image: adminer
    depends_on:
      - postgres
    links:
      - postgres:postgres
    networks:
      - postgresnetwork
    ports:
      - 8080:8080

networks:
  postgresnetwork:
    driver: bridge
